### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by rmiluzzi** [openpracticelibrary/openpracticelibrary#1044]
I would like to translate the website content into Portuguese. It would be possible?

**Comment by tdbeattie** [comment]
Hi @rmiluzzi - great suggestion! I don't think the current site has multi-lingual capabilities (but is something on the roadmap) so, for now, feel free to fork this repo and translate to Portuguese.

**Comment by juliaaano** [comment]
Building an automated translation capability would be a waste since a user can rely on the browser and/or google translate for that.
However, if a proper translation is required, it's a different story. The issue should be around multi lingual support/capability. Probably changes in Netlify that allows the translations be driven by the community.
@kattekrab I suggest closing this issue and creating another for multi-lingual support where the solution design can be properly described and discussed.

**Comment by kattekrab** [comment]
As suggested by @juliaaano  - we want a solution for multi-lingual - we already have a japanese fork - which is a good stepping stone, to eventual multi-lingual approach.
