### ISSUE TITLE
Social Contract Examples

### ISSUE THREAD

**Issue by charlesrichard** [openpracticelibrary/openpracticelibrary#117]
As a practitioner of Labs, I'd like example Social Contracts, both good and bad, to work from and demonstrate to teams.

**Comment by rdebeasi** [comment]
I can't think of an example where we've written a "bad" social contract - typically we guide people away from such things when facilitating this activity. I can imagine some examples, though:

## Don't do this

- Core hours are 9am-7pm.
- Be more productive by juggling several projects at once.
- Ensure accountability by finding someone to blame when things break.
- Deploying to production is scary because it's an opportunity to get blamed for something (see above). Could should be deployed as infrequently as possible.
- When you learn something, be sure to keep it to yourself so that everyone can see what a ninja rockstar wizard unicorn you are.

Alternately, below are my notes from facilitating a social contract activity a couple of months ago. (These were written with @kpennellaRH and @pcarney8. I think we also borrowed some ideas from @springdo).

## Consider doing this

- What sort of team culture do you want to build?
  - Open, positive, blame-free, constructive
  - Fun!
  - No magic, no wizardry, no ninjas - build shared understanding
- Celebrate success
- What core hours do you want to work?
  - 10am - 4pm?
- What are your thoughts on pair programming? Mob programming?
  - Mob to learn; pair to build?
  - Focus, then share what you learned?
  - Respect individual working styles
- How do you want to track tasks?
  - Jira
  - Paper stickies
  - Whatever the team chooses, commit to using that tool and communicating.
  - This helps us avoid missing important stuff or duplicating work.
- Embrace creative chaos

**Comment by rdebeasi** [comment]
Resolved by #372. Closing.
