### ISSUE TITLE
Bug: Clicking "Add a New Link" in Netlify errors out the preview screen

### ISSUE THREAD

**Issue by heyjerrybecker** [openpracticelibrary/openpracticelibrary#1334]
When a user updates a practice and clicks "Add a new link" in Netlify, the preview screen blanks out and shows the following error: (replicated on macOS/chrome)

![Screen Shot 2020-09-25 at 3 34 11 PM](https://user-images.githubusercontent.com/13509608/94308902-38dc2800-ff45-11ea-818f-8556b6076241.png)

**Comment by juliaaano** [comment]
Issue fixed by #1565.
Please review and merge @ https://deploy-preview-1565--openpracticelibrary.netlify.app
@kattekrab @heyjerrybecker

**Comment by juliaaano** [comment]
Found another issue with this, please hold for a while.

**Comment by juliaaano** [comment]
While testing the fix for this issue, I found another issue that is not really related at the codebase level.

When adding an invalid link URL value either in "LINKS WE LOVE" or "MEDIA GALLERY", the system is not able to validate the URL, so ti fails badly.

<img width="1497" alt="Screen Shot 2021-07-01 at 3 24 04 pm" src="https://user-images.githubusercontent.com/1110178/124070091-9d9e5300-da80-11eb-8c34-1f125675da55.png">

In the example, I edit an existing URL field and entered the number "1".

**Comment by juliaaano** [comment]
@kattekrab As part of this issue and related PR #1565, I've included the fixes for that other issue reported in my previous comment. Therefore, you have 3 things to validate:
1. Click the button "Add links we love" does not break the page.
2. Add any random value  in the "Link" field of "LINKS WE LOVE" does not break the page.
3. Add any random value in the "Media Link" of "MEDIA GALLERY" does not break the page.

**Comment by kattekrab** [comment]
Thanks @juliaaano I will take a look at this now
