### ISSUE TITLE
Can't find metrics based process mapping practice

### ISSUE THREAD

**Issue by kattekrab** [openpracticelibrary/openpracticelibrary#1510]
This exists: https://openpracticelibrary.com/practice/metrics-based-process-mapping/

But the filter can't find it...  looking for "met" "map" "pro" or even the whole string does not return the practice - so it's like it doesn't exist.  

Is this a bug?

**Comment by eranderson921** [comment]
It sure looks like a bug because if you filter on 'DISCOVERY' the MBPM practice is listed.  It just isn't in the list of 'ALL' (practices).

**Comment by kattekrab** [comment]
This has been reported before
 #1405

**Comment by eranderson921** [comment]
The exact same problem exists for practice "Measuring Psychological Safety".  I checked all the other practices and they appear in the list of 'ALL' practices.

**Comment by shaheinm** [comment]
This is happening because the `templateKey: practice-page` is missing from the practice markdown - this is **required** for the Gatsby to do its GraphQL query magic.

Haitham added it to the MBPM practice way back in October, but it was removed by a different commit (likely someone had an older version of OPL and ignored the merge conflicts) later that added a different practice.
