### ISSUE TITLE
Comment out youtube link in the footer or add content to the channel?

### ISSUE THREAD

**Issue by kattekrab** [openpracticelibrary/openpracticelibrary#1634]
https://github.com/openpracticelibrary/openpracticelibrary/blob/813ca7ccbcb683dd8f4ad5441f00e196becc224d/src/components/shared/BodyFooter/index.js#L85

Doing some use testing the other day, we discovered the youtube link points to a channel with no content.

Should we comment out the link for now?
Or add content to the channel?

@mtakane @heyjerrybecker @tdbeattie - what do you think?

**Comment by heyjerrybecker** [comment]
I’d love to use the channel for creating content that fills gaps in OPL (like when there isn’t a video walkthrough of impact mapping or something). That was the initial idea because we heard an overwhelming desire from users to see more visuals for practices.

We also had the idea of using it as a way to do sprint share ours - do it via YouTube live and allow for Q&A from attendees…but also have the recording on the channel so others can watch it later. It was an idea for how we might work “out in the open.”

So we can go either way with it, really. If we wanna start focusing on creating content or using it for shareouts, then let’s do it! If we’re not ready for that yet, then we can remove the link for now.

Best,
Jerry Becker

**Comment by kattekrab** [comment]
Those are great ideas! 

I wonder if we could make a start by linking to a playlist of videos already in the OPL?

**Comment by kattekrab** [comment]
Putting this here for safekeeping just in case I absent minded-ly delete the branch
```
<!--  Youtube channel is empty - let's comment this out until we have a playlist there.             
                <Grid item>
                <Link
                  href="https://www.youtube.com/channel/UCBGbB7xVsmf-yQ8NXn7TOVg?view_as=subscriber"
                  rel="noreferrer"
                  target="_blank"
                >
                  <YouTube />
                </Link>
              </Grid>
 -->  
```

**Comment by kattekrab** [comment]
I've made a pull request to remove the youtube link for now.
Tests are passing! Yay.
Here's a visual check.

![image](https://user-images.githubusercontent.com/172755/139582850-c9a77f2c-aae6-4a2f-831e-0bdfa53cfce3.png)

If that looks ok, I will need someone else to merge this in though.
