### ISSUE TITLE
CX - Fix TOKEN error preventing external contributions

### ISSUE THREAD

**Issue by kattekrab** [openpracticelibrary/openpracticelibrary#1813]
External contributors PRs can't be merged, cos the tests won't pass, cos they don't have access to our github environment variables.

eg.
Error: Please set NETLIFY_TOKEN env variable to your Netlify Personal Access Token secret
Error: Required field `site_id` was not provided

see https://github.com/openpracticelibrary/openpracticelibrary/runs/6032640396?check_suite_focus=true

**Comment by kattekrab** [comment]
This might be fixable via documentation, by providing contributor instructions on how to setup their own netlify tokens.  At least that's what @bproffitt suggested we should try!

**Comment by ahussey-redhat** [comment]
Did we end up working out what the process should be to specify our own token/how to generate our own token?

**Comment by kattekrab** [comment]
@ahussey-redhat not me, not yet!

**Comment by wengkee** [comment]
if there is a common netlify URL / token that can be used for this purpose, one way is to setup a secret at repository level or organization level, and point the github action file to use that

**Comment by kattekrab** [comment]
@wengkee do you want to have a go at setting that up?

**Comment by tim-stasse** [comment]
So the core of the issue here is that "Secrets are not passed to workflows that are triggered by a pull request from a fork".

This is a (security) feature, not a bug!

If it was allowed, it would make us vulnerable to potential threat actors who would then be able to steal our secrets by simply opening a PR (because the workflow would be executing untrusted code).

One solution to this is to migrate the end to end tests from a github action to a netlify build plugin, similar to what the [netlify team did themselves](https://www.netlify.com/blog/2021/06/22/migrating-cypress-tests-from-a-github-action-to-a-netlify-build-plugin/).

**Comment by kattekrab** [comment]
Thanks @tim-stasse - I thought this might be the case.  So yes, let's look into alternatives.  We definitely want to preserve the security feature.  Could we explore the build plugin idea?  Would it increase the cost of our builds on netlify?
