### ISSUE TITLE
Should we rename Social Contract, to Social Agreement?

### ISSUE THREAD

**Issue by kattekrab** [openpracticelibrary/openpracticelibrary#1831]
@ChrysSills99 thank you so much for this pull request!

There has been some off line discussion about changing the name from Social Contract, to Social Agreement.

Personally, I prefer Contract - but I appreciate that others have a different view, and don't want to reject the change without more input.  So, I'm going to open an issue for transparency and discussion. Let's see if we explore and document the reasons why this is a better name.

One of the things I like about using Social Contract as the name, is it echoes a common social philosophy, which informs the practice.  There's also this great article from 2012 in HBR - https://hbr.org/2012/04/to-ensure-great-teamwork-start

But I'm not opposed to change if there's a strong consensus it would be better to rename the practice to Social Agreement.

_Originally posted by @kattekrab in https://github.com/openpracticelibrary/openpracticelibrary/issues/1829#issuecomment-1166682182_

**Comment by tom-geraghty** [comment]
I'd add that Social Contract Theory is a well established sociological concept (possibly one of the oldest). 
I often encounter confusion when working with folks with a sociological or philosophical background, because talking about creating a "social contract", to them, sounds a bit like "let's recreate an existing social theory". 
In addition, social contract theory has some strong opposition in that it is seen as affirming the patriarchal oppression of anyone who isn't a man.
Personally, I'd lean towards changing it, but I also appreciate that two concepts can have the same name and mean different things :)

**Comment by rmarting** [comment]
IMHO I am more comfortable with "contract", as the set of rules defined by the team to set up the space of collaboration and work. I am not a legal expert, "agreement" or "contract" could have different meanings or use cases, also across different cultures and languages.

I would like to understand better why "agreement" is a better word for this practice. @ChrysSills99 could you give us more context about your proposal?

**Comment by eformat** [comment]
interesting. some googling points to

> Social contract theory says that people live together in society in accordance with an agreement that establishes moral and political rules of behavior

so nothing paternal in there specifically ?

**Comment by tom-geraghty** [comment]
> 

Worth reading stuff by Carole Pateman, who describes the patriarchal nature of the social contract: https://www.jstor.org/stable/2381814

I don't think this should influence the decision too much, but it's worth being aware that there are existing connotations and contexts associated with the term "social contract".

**Comment by eformat** [comment]
thanks a lot @tom-geraghty .. you have opened my eyes .. i couldn't really read behind the paywall/login thing on your link - but i have been researching a bit. 

these views are my own, but i will add here for the discussion:

i thought this was a good small summary of current Feminist Views on Social Contracting:
https://science.jrank.org/pages/11277/Social-Contract-Feminist-Views.html

It also seems there are contrary feminist views e.g. "Feminist Contractarianism" by Jean Hampton
https://www.taylorfrancis.com/chapters/edit/10.4324/9780429502682-15/feminist-contractarianism-jean-hampton

There was a good article/review from Carole Pateman on her seminal work - "The Sexual Contract 30 Years on: A Conversation with Carole Pateman"
https://link.springer.com/article/10.1007/s10691-018-9368-1
 
I sort of get the feeling that Carole Pateman is against all "contracting theory" in general. That (extreme ?) view is also written about here if you are interested:

-- "Feminism and the Social Contract"
https://www.patheos.com/blogs/faithpromotingrumor/2010/05/feminism-and-the-social-contract/

I also (now) totally recognize that the foundational work of "Social Contracting" was done a long time ago, by men who were from a different era (and yes, 2/3 of them were definitely sexist in my humble opinion !)

For a totally non-feminist view of Social Contracting and its history, this proved a pretty good of not long read:

-- "Contemporary Approaches to the Social Contract"
https://plato.stanford.edu/entries/contractarianism-contemporary

I quite liked the discussions of modelling agreement in the stanford entry, in particular:

- agreement is a “test” or a heuristic 
- [the] agreement is not itself a binding act - it is not a performative that somehow creates obligation

So, circling back to the proposed change .. i still feel that "Social Contract" is the right wording, we "want" it to be binding in some fashion wit respect to the way the practice is run ?

I think the term "Social Contract" can still be used with a "comtemporary" view, other examples of this terminology here for example - McKinsey:

-- "The social contract in the 21st century"
https://www.mckinsey.com/industries/public-and-social-sector/our-insights/the-social-contract-in-the-21st-century

**Comment by tom-geraghty** [comment]
Impressive work @eformat !

**Comment by kattekrab** [comment]
Elsewhere @ChrysSills99 indicated she's happy to close the PR changing the name, in favour of seeing "Agreement" as a variation, and opportunity for discussion with the team.   So I'll do that now.  @ChrysSills99 - I hope this is ok with you!?

Thanks everyone for the discussion here and exploring the issue so thoroughly!
🙏 😺

**Comment by ChrysSills99** [comment]
Oh I missed all the messaging.  Sorry to delay in sharing my thoughts.  I'm good with what the collective feels is the right thing.  At Red Hat we have been talking about how to use more Inclusive Language that establishes the agreement as a component of the overall collective "contract" for delivery.  

The **agreement** brings everyone together to collaborate and identify what they agree to socially hold each other accountable.  

The **contract** is what binds it.  

So is it the Activity that is the contract or the outcome that is the contract.  

What if it were adjusted to use both Agreement and Contract? 

**The activity you perform is the agreement exercise and the outcome is the binding of it via a contract.**

**Comment by eformat** [comment]
hi @ChrysSills99 .. i think you a conflating the two terms a little bit.

the *agreement* - is when everyone in the team agrees to the bahaviour being added to the social contract. you can agree with something but *not* be accountable to performing the actual behaviour.

the *contract* - signifies the *commitment* to the social contract as a whole. we do this when facilitating by asking everyone in the team to physically stand up and sign it. it seems like a token thing, but it is important.

let me give an example:

"sprint.0 - the team agrees to add "participate in a team lunch every thursday". everyone agrees this is a great idea, and facilitates team bonding. the team signs the social contract. some time later, not everyone is participating in team lunches on thursday. it is is brought up by one of the team members that the team is not adhering to the social contract. the team discusses, and decides to amend the social contract to team breakfasts on friday because everyone can make it on fridays. happy days."

in the example, people agreed but did not commit to changing their behaviour. they had more important things to do on thursday lunchtime.

so, it is both agreement and commitment that are important in Social Contracting. which is why it is termed that way, and not only "Social Agreement".

i am still failing to see how exactly the word "Contract" as used in the "Social Contract" practice is non-inclusive in this scenario ? we actually want to help drive behaviour change for the team.

**Comment by kattekrab** [comment]
Thanks for the discussion everyone.  Consensus suggests we stick with "contract" here, but there is nothing preventing people using "Agreement" in practice in the field.  I'm aware others use "Team charter" to cover this kind of agreement making too.  "A rose by any other name would smell as sweet" - the impact and outcome is in the doing and discussion!
