### ISSUE TITLE
Meditation Practice without author name

### ISSUE THREAD

**Issue by MaggiePerera** [openpracticelibrary/openpracticelibrary#1833]
I note that my Meditation practice does not have the author's name

https://openpracticelibrary.com/practice/meditation-to-generate-positive-emotions-for-the-team/

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/67352131/176564374-dedaf501-1dd3-4ba5-b6fe-596d8b535d86.png">

**Comment by rohandry** [comment]
The author listed on the practice must exactly match that listed in GitHub (Case Sensitive). 
In this case the issue was fixed by updating maggieperera to MaggiePerera.

As the current advice is to use only lower case:
"Comma-separated list of LOWER CASE github usernames eg., springdo, rdebeasi, tdbeattie"
I have submitted a change to update this to:
"Comma-separated list of case-sensitive github usernames eg., Springdo, rdebeasi, TdBeattie"

**Comment by tim-stasse** [comment]
Do we need to do anything with this for existing authors? i.e. are there more authors affected by this that we need to update, or can we close this now that the hint has been updated?

**Comment by rohandry** [comment]
Just clicked through the practices and found two more. 
1. https://openpracticelibrary.com/practice/minimum-viable-product-mvp/
2. https://openpracticelibrary.com/practice/c4-architecture/
The first does not seem to have a name listed on GitHub. 
The second seems to be correct already so perhaps a different issue. 
Otherwise the rest are good.

**Comment by kattekrab** [comment]
MVP practice is by https://github.com/DAppleyard93 
I've just updated @DAppleyard93's author page to be case sensitive too - see if that helps.
C4 is InfoSec812 - also just updated the author page there.
Tests running

**Comment by kattekrab** [comment]
merged, and deployed! 

Good catch @rohandry 

@MaggiePerera if you're happy, I think we can safely close this issue now!

**Comment by MaggiePerera** [comment]
Yes

> merged, and deployed!
> 
> Good catch @rohandry
> 
> @MaggiePerera if you're happy, I think we can safely close this issue now!

Yes @kattekrab close this issue please, and thanks a lot!
