### ISSUE TITLE
Suggestion for Improved Navigation - Shortcut to Home Page

### ISSUE THREAD

**Issue by JordiOlive** [openpracticelibrary/openpracticelibrary#2117]
I would like to suggest an enhancement to the navigation system. It would be convenient to have a direct shortcut to the home page, where all practices are listed, when navigating within a specific practice. This would save users from the need to use the browser's back button or navigate through menus to access the "View Library" option, which can be somewhat hidden. Adding an easily accessible link to the home page from within a practice would streamline the user experience

**Comment by kattekrab** [comment]
Yes! Great suggestion @JordiOlive . Do you have any suggestions on where best to put the link?

**Comment by kattekrab** [comment]
@JordiOlive - sorry it's taken so long - but I realised we could easily link the logo in the footer to the home page, so that's what I did! Could you please review the PR and deploy preview, and if this does the job for you, we can probably merge it.
#2154 - links footer to logo to home
https://deploy-preview-2154--openpracticelibrary.netlify.app/page/contribution-guide/

**Comment by kattekrab** [comment]
Thanks @JordiOlive - done!
