### ISSUE TITLE
update url to be 'open-practice-library' 

### ISSUE THREAD

**Issue by mtakane** [openpracticelibrary/openpracticelibrary#31]
To improve the SEO of the site and also increase url relevancy, we should use what we actually call this page in the URL.

**Comment by rdebeasi** [comment]
Options:
1. Rename this repo (this would break links on GitHub pages)
2. Create a new repo called "open-practice-library" and redirect the existing repo to the new one
3. Get a subdomain or domain for this project, using `open-practice-library`, and point it to GitHub pages. Use the canonical meta tag to point to the new domain.
4. Do option 3, and also switch to another hosting provider to make changes like these easier in the future.

**Comment by tenfourty** [comment]
Could we rename this repo and get a domain? openpracticelibrary.com is available...

Also for hosting, I highly recommend Netlify

**Comment by rdebeasi** [comment]
Sounds great!

As part of this change, we need web hooks and a build process (using openshift.com or RH's internal OpenShift cluster) to build and deploy when folks merge to master. (See #42). Right now, we check in the `docs` folder, and GitHub pages takes the deploy step for us.

**Comment by rdebeasi** [comment]
Awesome - I didn't realize that was a feature! Looks like it can even [run a hugo build](https://gohugo.io/hosting-and-deployment/hosting-on-netlify/) if needed.

I still like the idea of running builds in OpenShift/Jenkins so that we could say say that we build the practice library with the same tool set we use in residencies! :smile: Still, Netlify builds would be a great short-term solution if we get stuck with Jenkins builds.

**Comment by sherl0cks** [comment]
I have purchase openpracticelibrary.io and openpracticelibrary.com, as well as reserved  https://github.com/openpracticelibrary

**Comment by tdbeattie** [comment]
@mtakane @rdebeasi - just doing a tidy-up of old issues and came across this. 

I think we're all done with this now and should close?

**Comment by rdebeasi** [comment]
Thanks for catching! Yeah, we're done - closing. :pizza:
