### ISSUE TITLE
Provide A CI Job to Build the Hugo Page

### ISSUE THREAD

**Issue by sherl0cks** [openpracticelibrary/openpracticelibrary#42]
So you don't need to do it manually in the PR, as that is error prone.

**Comment by rdebeasi** [comment]
100% yes - we punted on that to get an MVP up and running, but it's probably time.

Alongside that, we should begin hosting this in OpenShift, Netlify, etc. because GitHub Pages requires you to check in compiled files (unless you're using Jekyll). We'd also need to get a new domain or subdomain for this.

https://github.com/redhat-cop/uncontained.io will eventually use OpenShift to build a Hugo site - maybe we can collaborate with that project on this work.

**Comment by sherl0cks** [comment]
ok - we should prob have a convo with @oybed on that. and probably once some customer work settles down.

**Comment by rdebeasi** [comment]
Work in progress: https://github.com/redhat-cop/uncontained.io/tree/master/container-images

**Comment by rdebeasi** [comment]
@jlosito definitely! The Uncontained.io folks are doing something similar to what you described. They'd be running builds with Jenkins instead of Travis, but the actual idea is the same.

**Comment by rdebeasi** [comment]
This is done with our new Netlify build!
