### ISSUE TITLE
"Visioning" Practice information seeking

### ISSUE THREAD

**Issue by mtakane** [openpracticelibrary/openpracticelibrary#445]
@alexismonville 

Reading through the related materials for this practice, it seems hard to understand how you would go about creating the vision. Is there another article that goes through typical questions to ask or some "How to" type information that can be provided?

I would like to see why this practice is of benefit as well. What will a user of this practice gain by doing this?

My hope is to see some of this content added to the practice eventually.

**Comment by alexismonville** [comment]
I agree @mtakane 
What I would like to do is to define the steps and give examples for each step and finish with an example of vision.

**Comment by rdebeasi** [comment]
I'd like to propose that we merge the "visioning" into [Start at the End](https://openpracticelibrary.com/practice/start-at-the-end/). Start at the End is a practice which allows participants to articulate a vision, so the two seem like a natural match.

Lean Service Creation sounds awesome, and since this toolkit was proposed we've added [Service Blueprint](https://openpracticelibrary.com/practice/service-blueprint/). This content would be a great addition to that practice!
