### ISSUE TITLE
Open Practice Library Card Decks - automating the generation

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#568]
We have been experimenting with using decks of cards (like playing cards) as a tool to explain and use the Open Practice Library.

At a couple of conference events, we have produced a Beta edition of an Open Practice Library deck of 36 cards. Each card has included Practice Name, one line description, detail on how long the practice takes, how many people are involved, the level of difficulty to facilitate and where the practice fits on the Library Loop. The reverse side of each card includes a QR code that, when scanned, takes the user to the relevant page in the Open Practice Library. The decks have also included canvases of the Library Loop which can be used to place cards around.

Community branding was applied to the cards and boxes brilliantly designed by @Rileyi 

Feedback from people who got their hands on one of these Beta editions has been very strong and there is a strong demand to produce more.

There are some challenges though, specifically:

- How do we keep the information on printed cards aligned to improvements and updates to practices in the Library?
- How do we facilitate adding cards for the many new practices appearing in the Library all the time?
- How do we reduce the repeatable design impact and manual effort to organise new print runs?

One idea, initially from @tenfourty, is to automate the process of card production. Could we build a small app that extracts the relevant meta-data from the Open Practice Library and creates a high quality PDF based on a predefined template? Users could then print their own selection of cards (or engage a printing company to produce decks of cards with the high quality PDFs). Perhaps we even open the possibility to customise / personalised the brand of cards.

Thoughts, ideas and suggestions very welcome.

**Comment by rdebeasi** [comment]
It would be awesome to automate the generation of the cards. A few questions (which we're also asking via email for folks who aren't on GitHub):

- What format do the printers need? Illustrator? PDF? Could they print from SVG? A really high-resolution PNG?
- What format are our source files in today? Sketch? A good starting point would be to get those files into a new repo under the openpracticelibrary org.

A few ideas for implementing this automation:
- Build something like [auto-diagram](https://github.com/rohitmusti/auto-diagram), which takes in info about a Labs residency and generates a PNG diagram.
- Use a [print stylesheet](https://www.smashingmagazine.com/2018/05/print-stylesheets-in-2018/), and some kind of script to generate images from the pages themselves. We'd have to make sure that we also allowed for normal printing.
- Use Hugo [output formats](https://gohugo.io/templates/output-formats/) to render SVG files instead of web pages. (SVGs can be converted to Illustrator format, if that's helpful for the printer.)

The [target outcomes](https://github.com/openpracticelibrary/openpracticelibrary/projects/3#card-15785551) for next week focus on the experience of finding, navigating, and understanding the site. Still, it would be great to see the cards moved to a format where we can iterate on them as quickly as we do the website. 

Further down the road, I'd love to see a way to purchase decks and either sell them at cost or donate the proceeds to charity.

**Comment by InfoSec812** [comment]
Spoke with Jana in the Open Innovation Labs marketing group and the format we provide to the printers is PDF with specifications for cuts/packaging/stock/colors/etc... I can point Red Hat teammates to the folder where the Illustrator source files and PDFs can be found. Also, I have a recommended printer for getting them made.

**Comment by InfoSec812** [comment]
@tdbeattie I love the idea of trying to automatically generate the PDFs for print-ready documents. Should/Could we also make it simple for our users to customize/print their own decks?

**Comment by andyfitz** [comment]
Red Hat has access to an enterprise http://outfit.io account.   
I'd suggest this as a valid option

**Comment by tdbeattie** [comment]
Moving this discussion to the Card Decks repo - https://github.com/openpracticelibrary/carddecks/issues/45
