### ISSUE TITLE
Add an Emerging Architecture practice

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#77]
@springdo - include the Big Picture for emerging infrastructure

**Comment by springdo** [comment]
Cool - I can take this!

**Comment by mtakane** [comment]
@tdbeattie @springdo what is thought on this as a practice. It seems like a perspective that would include a "Big Picture" practice.

**Comment by rdebeasi** [comment]
See also: https://submissions.agilealliance.org/system/attachments/attachments/000/000/2342/original/Emergent_Architecture_-_Just_Enough_Just_in_Time.pdf

**Comment by tdbeattie** [comment]
Yes. Now we've introduced the idea of "perspectives", i think that might be a better home for this.

**Comment by susanhasty** [comment]
Hello, I've been following this group and would like to contribute.   I'm a newbie so any advice or suggestions on "do's and don'ts" are welcome.  

There is an open source project around business architecture which I've recently joined the steering committee of.   You'll find the wiki at 
http://atf.architectural-thinking.com:8090/display/ATF/Architectural+Thinking+Framework

The website is https://architectural-thinking.com/

I'm wondering if there would be value in integrating this material with your library?

**Comment by susanhasty** [comment]
Wow!   This is exciting...my first open source contribution.  (%

**Comment by rdebeasi** [comment]
Hi @susanhasty - thanks for reaching out! We definitely welcome contributions.

Are there any practices within the Architectural Thinking Framework that can help teams discover and deliver digital products? If so, those would be great additions to the Open Practice Library! For more information, see the [contributing guide](https://openpracticelibrary.com/page/contributing/).

To be clear, this issue is focused on the architecture of software. I think the architecture of an entire organization might be outside the scope of the Open Practice Library, at least as it stands today.

Thanks again for your comment! :smile:

**Comment by lallmon** [comment]
Closing this out as Donal contributed the request, though any other related content is highly encouraged!

**Comment by kattekrab** [comment]
@lallmon and @springdo - I just went to add Ilaria's doodle for emerging architecture, but can't seem to find it!
Any chance you could help me? Was it called something else?

![Image](https://github.com/user-attachments/assets/778ed793-9045-448a-839e-89feefb57c85)

**Comment by kattekrab** [comment]
#2317

**Comment by kattekrab** [comment]
Oh - maybe it was added as a perspective...

**Comment by kattekrab** [comment]
@tdbeattie do you know where this might be hiding?

**Comment by kattekrab** [comment]
#1917
