### ISSUE TITLE
What is our stance on scrum language?

### ISSUE THREAD

**Issue by sherl0cks** [openpracticelibrary/openpracticelibrary#90]
Let's make a decision to use or not use scrum language.

See https://github.com/rht-labs/practice-library/pull/41#discussion_r178132821

**Comment by mtakane** [comment]
Being a culprit of not watching which terminology I use all the time, I like this question. I think we should look to normalize against use of Scrum terminology when possible. Since we look to include so much more than just Scrum and people have preconceived notions about those terms, we should look to be agnostic of methodology as much as possible.

**Comment by tdbeattie** [comment]
A few thoughts:

- Agree that we include much more than Scrum - perhaps we can label practices that are Scrum-based (or Iterative Delivery based) and highlight that many of the practices we have in our library sit outside Scrum (e.g. Discovery based, Tech/Engineering based.

- I personally find it difficult to avoid using the term "ScrumMaster". I've seen the term "Iteration Manager" used in its place which doesn't wash with me that well (as such people should be strong servant leaders rather than managers). 

- Many of our customers are adopting Scrum and/or Kanban within their own organisations and using terminology. Trying to change this may cause confusion and discontent.

- AFAIK, our product engineering adopts Scrum and Kanban where an agile approach is being taken. I see the latest State of Scrum report has a big article on Red Hat - https://www.scrumalliance.org/ScrumRedesignDEVSite/media/ScrumAllianceMedia/Files%20and%20PDFs/State%20of%20Scrum/2017-SoSR-Final-Version-(Pages).pdf - as Labs is all about open-sourcing our DNA, perhaps it is appropraite to stay close to Scrum?

**Comment by rdebeasi** [comment]
I second the idea of being as agnostic as possible. I don't think we should pretend that Scrum doesn't exist, but I think we should treat it like any other philosophy or source of ideas.

I think it's ok to use Scrum-derived terms as long as:
- They're widely used outside of Labs and Red Hat
- The alternative is non-Scrum jargon
- We don't assume that the reader knows or wants to practice Scrum

To put it another way: align with de facto standards, but strive for broad compatibility.

For example, the term "scrum master" is ok because it's widely used, "iteration manager" is just more jargon, and plain-English words like "facilitator" or "manager" doesn't really get across that servant-leader concept.

On the other hand, "Sprint zero" isn't a good term to use because it's not widely used (even in scrum teams), and "Prep Week" gets across the same meaning without adding jargon.

Thoughts?

---

Side note: we sometimes run "Kanban lite" when we're short on time, so even within Labs we're not practicing strict Scrum.

**Comment by rdebeasi** [comment]
This article from @mtakane and others says it better than I could: https://opensource.com/article/18/10/what-agile

**Comment by lallmon** [comment]
Closing this as it seems the consensus seems to be the one you came to about mindset and tooling as opposed to specific processes and ceremonies. :+1: :100:
